name: Amazon Auto Sourcing

on:
  schedule:
    - cron: '0 22 * * 0'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install libraries
        run: |
          pip install requests
          pip install beautifulsoup4
          pip install pandas
          pip install deep-translator

      - name: Run python main.py
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
        run: python main.py
